const actionType = {
  CHANGE_SEARCH_FIELD: "CHANGE_SEARCH_FIELD",
  FETCH_ROBOTS_PENDING: "FETCH_ROBOTS_PENDING",
  FETCH_ROBOTS_SUCCESS: "FETCH_ROBOTS_SUCCESS",
  FETCH_ROBOTS_FAILED: "FETCH_ROBOTS_FAILED",
};
export default actionType;
